ccflags-y += -I$(srctree)/drivers/misc/mediatek/hdmi/inc  \
             -I$(srctree)/drivers/misc/mediatek/include/ \
             -I$(srctree)/drivers/misc/mediatek/video/$(MTK_PLATFORM)/ \
             -I$(srctree)/drivers/misc/mediatek/video/$(MTK_PLATFORM)/dispsys/ \
             -I$(srctree)/drivers/misc/mediatek/ext_disp/$(MTK_PLATFORM)/

subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/mmp/

obj-y	+= hdmi_drv.o siHdmiTx_902x_TPI.o
